import type { Doc } from './_generated/dataModel';

/** Starter catalogue — expand via dashboard or admin seed (see usermenu.md). */
export type BadgeDefinitionSeed = Omit<
  Doc<'badgeDefinitions'>,
  '_id' | '_creationTime'
>;

export const BADGE_DEFINITION_SEEDS: BadgeDefinitionSeed[] = [
  // Getting Started
  {
    slug: 'first_steps',
    category: 'getting_started',
    label: 'First Steps',
    description: 'Record your first walk',
    sortOrder: 1,
    iconKey: 'boot',
    criteriaType: 'walk_count',
    criteriaThreshold: 1,
    isActive: true,
  },
  {
    slug: 'route_rookie',
    category: 'getting_started',
    label: 'Route Rookie',
    description: 'Plan your first route',
    sortOrder: 2,
    iconKey: 'map',
    criteriaType: 'planned_route_count',
    criteriaThreshold: 1,
    isActive: true,
  },
  {
    slug: 'profile_ready',
    category: 'getting_started',
    label: 'Profile Ready',
    description: 'Add an avatar to your profile',
    sortOrder: 6,
    iconKey: 'person',
    criteriaType: 'has_avatar',
    criteriaThreshold: 1,
    isActive: true,
  },
  {
    slug: 'goal_setter',
    category: 'getting_started',
    label: 'Goal Setter',
    description: 'Create your first walking goal',
    sortOrder: 8,
    iconKey: 'target',
    criteriaType: 'goal_created',
    criteriaThreshold: 1,
    isActive: true,
  },
  {
    slug: 'beta_explorer',
    category: 'getting_started',
    label: 'Rambleio Beta Explorer',
    description: 'Joined during the beta programme',
    sortOrder: 10,
    iconKey: 'star',
    criteriaType: 'joined_beta',
    criteriaThreshold: 1,
    isActive: true,
  },
  // Distance milestones (metres)
  {
    slug: 'distance_1km',
    category: 'distance_milestones',
    label: '1 km Walked',
    description: 'Walk a total of 1 km',
    sortOrder: 1,
    iconKey: 'distance',
    criteriaType: 'total_distance_m',
    criteriaThreshold: 1000,
    isActive: true,
  },
  {
    slug: 'distance_5km',
    category: 'distance_milestones',
    label: '5 km Walked',
    description: 'Walk a total of 5 km',
    sortOrder: 2,
    iconKey: 'distance',
    criteriaType: 'total_distance_m',
    criteriaThreshold: 5000,
    isActive: true,
  },
  {
    slug: 'distance_10km',
    category: 'distance_milestones',
    label: '10 km Walked',
    description: 'Walk a total of 10 km',
    sortOrder: 3,
    iconKey: 'distance',
    criteriaType: 'total_distance_m',
    criteriaThreshold: 10000,
    isActive: true,
  },
  {
    slug: 'distance_25km',
    category: 'distance_milestones',
    label: '25 km Total',
    description: 'Walk a total of 25 km',
    sortOrder: 4,
    iconKey: 'distance',
    criteriaType: 'total_distance_m',
    criteriaThreshold: 25000,
    isActive: true,
  },
  {
    slug: 'distance_100km',
    category: 'distance_milestones',
    label: '100 km Total',
    description: 'Walk a total of 100 km',
    sortOrder: 6,
    iconKey: 'distance',
    criteriaType: 'total_distance_m',
    criteriaThreshold: 100000,
    isActive: true,
  },
];
