import type { Doc } from './_generated/dataModel';

export type BadgeCategorySeed = Omit<Doc<'badgeCategories'>, '_id' | '_creationTime'>;

/** Ten category blocks from the Rambleio badges mockup (@see docs/badgeSystemRoadmap.md). */
export const BADGE_CATEGORY_SEEDS: BadgeCategorySeed[] = [
  {
    key: 'getting_started',
    name: 'Getting Started',
    description: 'Onboarding milestones for new walkers.',
    color: '#4F8A3D',
    icon: 'boot',
    displayOrder: 1,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'distance_milestones',
    name: 'Distance',
    description: 'Total distance and long-walk achievements.',
    color: '#E65100',
    icon: 'distance',
    displayOrder: 2,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'consistency',
    name: 'Consistency',
    description: 'Streaks and regular walking habits.',
    color: '#008C8C',
    icon: 'calendar',
    displayOrder: 3,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'monthly_challenges',
    name: 'Monthly Challenges',
    description: 'Calendar-month walking targets.',
    color: '#7E57C2',
    icon: 'month',
    displayOrder: 4,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'exploration',
    name: 'Exploration',
    description: 'Discover new places and terrain types.',
    color: '#2F80C9',
    icon: 'compass',
    displayOrder: 5,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'route_planning',
    name: 'Route Planning',
    description: 'Plan and publish walking routes.',
    color: '#7A8F2A',
    icon: 'map',
    displayOrder: 6,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'recording_quality',
    name: 'Recording Quality',
    description: 'High-quality walk recordings.',
    color: '#D99A16',
    icon: 'gps',
    displayOrder: 7,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'elevation',
    name: 'Elevation',
    description: 'Climbing and ascent milestones.',
    color: '#6D4C41',
    icon: 'mountain',
    displayOrder: 8,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'following_routes',
    name: 'Following Routes',
    description: 'Follow planned routes and stay on track.',
    color: '#C94A68',
    icon: 'route',
    displayOrder: 9,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    key: 'community_sharing',
    name: 'Community / Sharing',
    description: 'Share walks and contribute to the community.',
    color: '#5B4BB2',
    icon: 'share',
    displayOrder: 10,
    isActive: true,
    createdAt: 0,
    updatedAt: 0,
  },
];
